theme: just-the-docs
title: r/HomeKitAutomation Wiki
description: This is the official Wiki for r/HomeKitAutomation!
logo: "https://styles.redditmedia.com/t5_4iwqqk/styles/communityIcon_q4v8i8am2tb71.jpg?width=256&s=a25f3b7bc8d2731454b6c54c61b38c9240df46b8"
